"""Add meeting and attendance tracking tables

Revision ID: f4e7d8b9c123
Revises: 843c768c33cd
Create Date: 2024-12-19 19:03:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4e7d8b9c123'
down_revision: Union[str, None] = '843c768c33cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facilitator_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=True),
    sa.Column('location_address', sa.String(length=500), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('agenda', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_circle_id'), 'meetings', ['circle_id'], unique=False)
    op.create_index(op.f('ix_meetings_facilitator_id'), 'meetings', ['facilitator_id'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_date'), 'meetings', ['scheduled_date'], unique=False)
    
    op.create_table('meeting_attendance',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id')
    )
    op.create_index(op.f('ix_meeting_attendance_meeting_id'), 'meeting_attendance', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendance_user_id'), 'meeting_attendance', ['user_id'], unique=False)

    # Add meetings relationship to circles table - this is handled by the Circle model relationship definition
    # No schema changes needed for the relationship as it's handled by foreign keys
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_attendance_user_id'), table_name='meeting_attendance')
    op.drop_index(op.f('ix_meeting_attendance_meeting_id'), table_name='meeting_attendance')
    op.drop_table('meeting_attendance')
    op.drop_index(op.f('ix_meetings_scheduled_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_facilitator_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_circle_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ### 