"""add_google_oauth_fields

Revision ID: a1b2c3d4e5f6
Revises: d9aa8768cf02
Create Date: 2024-12-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'd9aa8768cf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('google_user_id', sa.String(length=255), nullable=True))
    op.add_column('user_credentials', sa.Column('google_access_token', sa.LargeBinary(), nullable=True))
    op.add_column('user_credentials', sa.Column('google_refresh_token', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint('uq_user_credentials_google_user_id', 'user_credentials', ['google_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_credentials_google_user_id', 'user_credentials', type_='unique')
    op.drop_column('user_credentials', 'google_refresh_token')
    op.drop_column('user_credentials', 'google_access_token')
    op.drop_column('user_credentials', 'google_user_id')
    # ### end Alembic commands ### 