"""add_password_reset_fields

Revision ID: c4b0e5c7784e
Revises: a1b2c3d4e5f6
Create Date: 2025-06-08 22:20:58.491530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b0e5c7784e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('user_credentials', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_credentials', sa.Column('password_reset_attempts', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'password_reset_attempts')
    op.drop_column('user_credentials', 'password_reset_expires_at')
    op.drop_column('user_credentials', 'password_reset_token')
    # ### end Alembic commands ###
