"""add_phone_verification_fields

Revision ID: d9aa8768cf02
Revises: 1e978f7e8aa5
Create Date: 2025-06-08 14:54:47.798340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aa8768cf02'
down_revision: Union[str, None] = '1e978f7e8aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('phone_verification_code', sa.String(length=10), nullable=True))
    op.add_column('user_credentials', sa.Column('phone_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_credentials', sa.Column('phone_verification_attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'phone_verification_attempts')
    op.drop_column('user_credentials', 'phone_verification_expires_at')
    op.drop_column('user_credentials', 'phone_verification_code')
    # ### end Alembic commands ###
